name: "Generate and update JSON Spec lists for translation"
on:
  push:
    branches:
      - dev
    paths:
      - 'P5/Source/Specs/*.xml'

jobs:
  build:
    if: github.repository == 'TEIC/TEI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/generate-spec-lists
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Re-generated spec lists.
      