name: "Generate and update JSON Spec lists for translation"
on:
  push:
    paths:
      - 'P5/Source/Specs/*.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout TEI Repository
        uses: actions/checkout@v3
        
      - name: Fix permissions   
        run: git config --global --add safe.directory /__w/TEI/TEI
        
      - name: Generate JSON Spec list        
        uses: ./.github/actions/generate-spec-lists
        
      - name: Auto-commit Spec list  
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: ${{ github.actor }}
          commit_message: Re-generated spec lists.
      
